apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edgion-system
resources:
  - namespace.yaml
  - crd.yaml
  - service-account.yaml
  - rbac.yaml
  - config.yaml
  - service.yaml
  - deployment.yaml
  - pdb.yaml
