import { useEffect, useState } from 'react'
import { Button, Card, Checkbox, Form, Input, InputNumber, Modal, Select, Space, Tabs, message } from 'antd'
import { MinusCircleOutlined, PlusOutlined } from '@ant-design/icons'
import MetadataSection from '../common/MetadataSection'
import YamlEditor from '@/components/YamlEditor'
import { editorCancelButtonProps, editorFormTab, editorSubmitButtonProps, editorYamlTab } from '../editorTestIds'
import { createEmptyEndpointSlice, endpointSliceFromYaml, endpointSliceToYaml, normalizeEndpointSlice, validateEndpointSlice, type EndpointSliceResource } from '@/utils/endpointslice'

type Props = { visible: boolean; mode: 'create'|'edit'|'view'; resource?: unknown; onClose:()=>void; onSubmit:(yaml:string, value:EndpointSliceResource)=>Promise<void> }
export default function EndpointSliceEditor({visible,mode,resource,onClose,onSubmit}:Props){
  const [draft,setDraft]=useState<EndpointSliceResource>(createEmptyEndpointSlice); const [yaml,setYaml]=useState(''); const [tab,setTab]=useState('form'); const [saving,setSaving]=useState(false); const readonly=mode==='view'
  useEffect(()=>{if(!visible)return;const next=mode==='create'?createEmptyEndpointSlice():normalizeEndpointSlice(resource);setDraft(next);setYaml(endpointSliceToYaml(next,mode==='create'?'create':'update'));setTab('form')},[visible,mode,resource])
  const switchTab=(key:string)=>{try{if(key==='yaml')setYaml(endpointSliceToYaml(draft,mode==='create'?'create':'update'));else setDraft(endpointSliceFromYaml(yaml));setTab(key)}catch(e){message.error((e as Error).message)}}
  const save=async()=>{try{const value=tab==='form'?draft:endpointSliceFromYaml(yaml);validateEndpointSlice(value);if(mode==='edit'){const old=normalizeEndpointSlice(resource);if(value.metadata.name!==old.metadata.name||value.metadata.namespace!==old.metadata.namespace)throw new Error('EndpointSlice cannot be renamed')}setSaving(true);await onSubmit(endpointSliceToYaml(value,mode==='create'?'create':'update'),value)}catch(e){message.error((e as Error).message)}finally{setSaving(false)}}
  const serviceName=draft.metadata.labels?.['kubernetes.io/service-name']||''; const ports=draft.ports??[]
  return <Modal open={visible} onCancel={onClose} width={900} title={`${mode==='create'?'Create':mode==='edit'?'Edit':'View'} EndpointSlice`} footer={readonly?<Button {...editorCancelButtonProps} onClick={onClose}>Close</Button>:<><Button {...editorCancelButtonProps} onClick={onClose}>Cancel</Button><Button {...editorSubmitButtonProps} type="primary" loading={saving} onClick={save}>Save</Button></>}>
    <Tabs activeKey={tab} onChange={switchTab} items={[{key:'form',label:editorFormTab('Form'),children:<Form layout="vertical"><MetadataSection value={draft.metadata} disabled={readonly} isCreate={mode==='create'} onChange={(metadata)=>setDraft({...draft,metadata:{...draft.metadata,...metadata,namespace:metadata.namespace||''}})} />
      <Space wrap><Form.Item label="Service name"><Input disabled={readonly} value={serviceName} onChange={(e)=>setDraft({...draft,metadata:{...draft.metadata,labels:{...draft.metadata.labels,'kubernetes.io/service-name':e.target.value}}})}/></Form.Item><Form.Item label="Address type"><Select disabled={readonly} style={{width:140}} value={draft.addressType} options={['IPv4','IPv6','FQDN'].map(value=>({value}))} onChange={(addressType)=>setDraft({...draft,addressType})}/></Form.Item></Space>
      <Card size="small" title="Ports">{ports.map((port,i)=><Space key={i} style={{marginBottom:8}}><Input disabled={readonly} placeholder="name" value={port.name} onChange={(e)=>{const next=[...ports];next[i]={...port,name:e.target.value};setDraft({...draft,ports:next})}}/><InputNumber disabled={readonly} min={1} max={65535} value={port.port} placeholder="port" onChange={(value)=>{const next=[...ports];next[i]={...port,port:value??undefined};setDraft({...draft,ports:next})}}/><Select disabled={readonly} value={port.protocol||'TCP'} style={{width:100}} options={['TCP','UDP','SCTP'].map(value=>({value}))} onChange={(protocol)=>{const next=[...ports];next[i]={...port,protocol};setDraft({...draft,ports:next})}}/>{!readonly&&<Button data-testid="endpointslice-port-remove" danger type="text" icon={<MinusCircleOutlined/>} onClick={()=>setDraft({...draft,ports:ports.filter((_,x)=>x!==i)})}/>}</Space>)}{!readonly&&<Button data-testid="endpointslice-port-add" type="dashed" icon={<PlusOutlined/>} onClick={()=>setDraft({...draft,ports:[...ports,{port:80,protocol:'TCP'}]})}>Add port</Button>}</Card>
      <Card size="small" title="Endpoints" style={{marginTop:12}}>{draft.endpoints.map((endpoint,i)=><Card key={i} size="small" style={{marginBottom:8}} extra={!readonly&&<Button danger type="text" icon={<MinusCircleOutlined/>} onClick={()=>setDraft({...draft,endpoints:draft.endpoints.filter((_,x)=>x!==i)})}/>}><Form.Item label="Addresses (comma separated)"><Input disabled={readonly} value={endpoint.addresses.join(', ')} onChange={(e)=>{const next=[...draft.endpoints];next[i]={...endpoint,addresses:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)};setDraft({...draft,endpoints:next})}}/></Form.Item><Space><Checkbox disabled={readonly} checked={endpoint.conditions?.ready} onChange={(e)=>{const next=[...draft.endpoints];next[i]={...endpoint,conditions:{...endpoint.conditions,ready:e.target.checked}};setDraft({...draft,endpoints:next})}}>Ready</Checkbox><Checkbox disabled={readonly} checked={endpoint.conditions?.serving} onChange={(e)=>{const next=[...draft.endpoints];next[i]={...endpoint,conditions:{...endpoint.conditions,serving:e.target.checked}};setDraft({...draft,endpoints:next})}}>Serving</Checkbox><Input disabled={readonly} placeholder="hostname" value={endpoint.hostname} onChange={(e)=>{const next=[...draft.endpoints];next[i]={...endpoint,hostname:e.target.value};setDraft({...draft,endpoints:next})}}/></Space></Card>)}{!readonly&&<Button type="dashed" icon={<PlusOutlined/>} onClick={()=>setDraft({...draft,endpoints:[...draft.endpoints,{addresses:[],conditions:{ready:true}}]})}>Add endpoint</Button>}</Card>
    </Form>},{key:'yaml',label:editorYamlTab('YAML'),children:<YamlEditor value={yaml} onChange={setYaml} readOnly={readonly} height="520px"/>}]} />
  </Modal>
}
