import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, InputNumber, Modal, Select, Space, Tabs, message } from 'antd'
import { MinusCircleOutlined, PlusOutlined } from '@ant-design/icons'
import MetadataSection from '../common/MetadataSection'
import YamlEditor from '@/components/YamlEditor'
import { editorCancelButtonProps, editorFormTab, editorSubmitButtonProps, editorYamlTab } from '../editorTestIds'
import { createEmptyService, normalizeService, serviceFromYaml, serviceToYaml, validateService, type ServiceResource } from '@/utils/service'

type Props = { visible: boolean; mode: 'create' | 'edit' | 'view'; resource?: unknown; onClose: () => void; onSubmit: (yaml: string, resource: ServiceResource) => Promise<void> }
const setMapEntry = (map: Record<string, string>, oldKey: string, key: string, value: string) => { const next = { ...map }; delete next[oldKey]; if (key) next[key] = value; return next }

export default function ServiceEditor({ visible, mode, resource, onClose, onSubmit }: Props) {
  const [draft, setDraft] = useState<ServiceResource>(createEmptyService)
  const [yaml, setYaml] = useState(''); const [tab, setTab] = useState('form'); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!visible) return; const next = mode === 'create' ? createEmptyService() : normalizeService(resource); setDraft(next); setYaml(serviceToYaml(next, mode === 'create' ? 'create' : 'update')); setTab('form') }, [visible, mode, resource])
  const readonly = mode === 'view'
  const switchTab = (key: string) => { try { if (key === 'yaml') setYaml(serviceToYaml(draft, mode === 'create' ? 'create' : 'update')); else setDraft(serviceFromYaml(yaml)); setTab(key) } catch (e) { message.error((e as Error).message) } }
  const save = async () => { try { const value = tab === 'form' ? draft : serviceFromYaml(yaml); validateService(value); if (mode === 'edit') { const old = normalizeService(resource); if (value.metadata.name !== old.metadata.name || value.metadata.namespace !== old.metadata.namespace) throw new Error('Service cannot be renamed') } setSaving(true); await onSubmit(serviceToYaml(value, mode === 'create' ? 'create' : 'update'), value); } catch (e) { message.error((e as Error).message) } finally { setSaving(false) } }
  const selector = draft.spec.selector ?? {}; const ports = draft.spec.ports ?? []
  return <Modal open={visible} onCancel={onClose} width={900} title={`${mode === 'create' ? 'Create' : mode === 'edit' ? 'Edit' : 'View'} Service`} footer={readonly ? <Button {...editorCancelButtonProps} onClick={onClose}>Close</Button> : <><Button {...editorCancelButtonProps} onClick={onClose}>Cancel</Button><Button {...editorSubmitButtonProps} type="primary" loading={saving} onClick={save}>Save</Button></>}>
    <Tabs activeKey={tab} onChange={switchTab} items={[{ key: 'form', label: editorFormTab('Form'), children: <Form layout="vertical"><MetadataSection value={draft.metadata} disabled={readonly} isCreate={mode === 'create'} onChange={(metadata) => setDraft({ ...draft, metadata: { ...draft.metadata, ...metadata, namespace: metadata.namespace || '' } })} />
      <Card size="small" title="Service"><Space wrap><Form.Item label="Type"><Select disabled={readonly} value={draft.spec.type} style={{ width: 180 }} options={['ClusterIP','NodePort','LoadBalancer','ExternalName'].map(value => ({ value }))} onChange={(type) => setDraft({ ...draft, spec: { ...draft.spec, type } })} /></Form.Item>{draft.spec.type === 'ExternalName' && <Form.Item label="External name"><Input disabled={readonly} value={draft.spec.externalName} onChange={(e) => setDraft({ ...draft, spec: { ...draft.spec, externalName: e.target.value } })} /></Form.Item>}<Form.Item label="Session affinity"><Select disabled={readonly} value={draft.spec.sessionAffinity || 'None'} options={['None','ClientIP'].map(value => ({ value }))} onChange={(sessionAffinity) => setDraft({ ...draft, spec: { ...draft.spec, sessionAffinity } })} /></Form.Item></Space></Card>
      <Card size="small" title="Selector" style={{ marginTop: 12 }}>{Object.entries(selector).map(([key,value]) => <Space key={key} style={{ marginBottom: 8 }}><Input disabled={readonly} value={key} onChange={(e) => setDraft({ ...draft, spec: { ...draft.spec, selector: setMapEntry(selector, key, e.target.value, value) } })} /><Input disabled={readonly} value={value} onChange={(e) => setDraft({ ...draft, spec: { ...draft.spec, selector: { ...selector, [key]: e.target.value } } })} />{!readonly && <Button danger type="text" icon={<MinusCircleOutlined />} onClick={() => setDraft({ ...draft, spec: { ...draft.spec, selector: setMapEntry(selector,key,'','') } })} />}</Space>)}{!readonly && <Button type="dashed" icon={<PlusOutlined />} onClick={() => setDraft({ ...draft, spec: { ...draft.spec, selector: { ...selector, [`key-${Object.keys(selector).length+1}`]: '' } } })}>Add selector</Button>}</Card>
      <Card size="small" title="Ports" style={{ marginTop: 12 }}>{ports.map((port,index) => <Space key={index} align="start" style={{ marginBottom: 8 }}><Input disabled={readonly} placeholder="name" value={port.name} onChange={(e) => { const next=[...ports]; next[index]={...port,name:e.target.value}; setDraft({...draft,spec:{...draft.spec,ports:next}}) }} /><InputNumber disabled={readonly} min={1} max={65535} placeholder="port" value={port.port} onChange={(value) => { const next=[...ports]; next[index]={...port,port:value ?? 80}; setDraft({...draft,spec:{...draft.spec,ports:next}}) }} /><Input disabled={readonly} placeholder="targetPort" value={port.targetPort} onChange={(e) => { const v=e.target.value; const next=[...ports]; next[index]={...port,targetPort:/^\d+$/.test(v)?Number(v):v}; setDraft({...draft,spec:{...draft.spec,ports:next}}) }} /><Select disabled={readonly} value={port.protocol || 'TCP'} style={{width:100}} options={['TCP','UDP','SCTP'].map(value=>({value}))} onChange={(protocol) => {const next=[...ports];next[index]={...port,protocol};setDraft({...draft,spec:{...draft.spec,ports:next}})}} />{!readonly && <Button danger type="text" icon={<MinusCircleOutlined />} onClick={() => setDraft({...draft,spec:{...draft.spec,ports:ports.filter((_,i)=>i!==index)}})} />}</Space>)}{!readonly && <Button type="dashed" icon={<PlusOutlined />} onClick={() => setDraft({...draft,spec:{...draft.spec,ports:[...ports,{port:80,protocol:'TCP'}]}})}>Add port</Button>}</Card>
    </Form> }, { key: 'yaml', label: editorYamlTab('YAML'), children: <YamlEditor value={yaml} onChange={setYaml} readOnly={readonly} height="520px" /> }]} />
  </Modal>
}
